### ISSUE TITLE
yarn compile not generate typeechained folder in section of Add TypeChain plugin

### ISSUE THREAD

**Issue by zhangyongzhe20** [BlockchainCourseNTU/hello-dapp#14]

**Comment by zhangyongzhe20** [comment]
It seems that the typechained folder is not generated, cause it's cannot be found in during test. 
![image](https://user-images.githubusercontent.com/29170817/135050200-3864e102-7ec2-4e91-bdbb-eb705e933bc3.png)

**Comment by alxiong** [comment]
@zhangyongzhe20  did you add `import '@typechain/hardhat';` in your `hardhat.config.ts`?

**Comment by zhangyongzhe20** [comment]
The typechained folder is generated after running `yarn compile --force`. Thanks @alxiong
